version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      DB_USUARIO: root
      DB_NOME: goexpert
      DB_SENHA: root
    ports:
      - 3306:3306
